<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title></title>
<style type="text/css">
.ansi2html-content { display: inline; white-space: pre-wrap; word-wrap: break-word; }
.body_foreground { color: #AAAAAA; }
.body_background { background-color: #000000; }
.body_foreground > .bold,.bold > .body_foreground, body.body_foreground > pre > .bold { color: #FFFFFF; font-weight: normal; }
.inv_foreground { color: #000000; }
.inv_background { background-color: #AAAAAA; }
</style>
</head>
<body class="body_foreground body_background" style="font-size: normal;" >
<pre class="ansi2html-content">
2020-01-06 21:09:25 default INFO cinder.volume.drivers.hpe.hpe_3par_common [-] HPE3PARCommon 4.0.14,hpe3parclient 4.2.11
2020-01-06 21:09:25 default DEBUG cinder.volume.drivers.hpe.hpe_3par_common [-] Connecting to 3PAR client_login /usr/lib/python2.7/site-packages/cinder/volume/drivers/hpe/hpe_3par_common.py:410
2020-01-06 21:09:26 default DEBUG cinder.volume.drivers.hpe.hpe_3par_common [-] Disconnect from 3PAR REST and SSH 75dc2f82-bb90-4b54-9b73-bdda7bbee16c client_logout /usr/lib/python2.7/site-packages/cinder/volume/drivers/hpe/hpe_3par_common.py:434
2020-01-06 21:09:26 default DEBUG cinder.volume.drivers.hpe.hpe_3par_common [-] Connecting to 3PAR client_login /usr/lib/python2.7/site-packages/cinder/volume/drivers/hpe/hpe_3par_common.py:410
2020-01-06 21:09:26 default ERROR cinder.volume.drivers.hpe.hpe_3par_common [-] CPG (S) doesn't exist on array: HTTPNotFound: Not found (HTTP 404) 15 - CPG does not exist
2020-01-06 21:09:26 default DEBUG cinder.volume.drivers.hpe.hpe_3par_common [-] Disconnect from 3PAR REST and SSH 75dc2f82-bb90-4b54-9b73-bdda7bbee16c client_logout /usr/lib/python2.7/site-packages/cinder/volume/drivers/hpe/hpe_3par_common.py:434
2020-01-06 21:09:26 default CRITICAL cinder [-] Unhandled error: InvalidInput: Invalid input received: CPG (S) doesn't exist on array
2020-01-06 21:09:26.326 1 ERROR cinder Traceback (most recent call last):
2020-01-06 21:09:26.326 1 ERROR cinder   File "/usr/bin/ember-csi", line 9, in &lt;module&gt;
2020-01-06 21:09:26.326 1 ERROR cinder     load_entry_point('ember-csi==master-06012020210903640135092', 'console_scripts', 'ember-csi')()
2020-01-06 21:09:26.326 1 ERROR cinder   File "/ember-csi/ember_csi/ember_csi.py", line 79, in main
2020-01-06 21:09:26.326 1 ERROR cinder     node_id=node_id)
2020-01-06 21:09:26.326 1 ERROR cinder   File "/ember-csi/ember_csi/v1_0_0/csi.py", line 55, in __init__
2020-01-06 21:09:26.326 1 ERROR cinder     ember_config=ember_config)
2020-01-06 21:09:26.326 1 ERROR cinder   File "/ember-csi/ember_csi/v1_0_0/csi_base.py", line 42, in __init__
2020-01-06 21:09:26.326 1 ERROR cinder     **kwargs)
2020-01-06 21:09:26.326 1 ERROR cinder   File "/ember-csi/ember_csi/base.py", line 312, in __init__
2020-01-06 21:09:26.326 1 ERROR cinder     self.backend = cinderlib.Backend(**backend_config)
2020-01-06 21:09:26.326 1 ERROR cinder   File "/usr/lib/python2.7/site-packages/cinderlib/cinderlib.py", line 87, in __init__
2020-01-06 21:09:26.326 1 ERROR cinder     self.driver.do_setup(objects.CONTEXT)
2020-01-06 21:09:26.326 1 ERROR cinder   File "/usr/lib/python2.7/site-packages/cinder/volume/drivers/hpe/hpe_3par_base.py", line 437, in do_setup
2020-01-06 21:09:26.326 1 ERROR cinder     common.check_for_setup_error()
2020-01-06 21:09:26.326 1 ERROR cinder   File "/usr/lib/python2.7/site-packages/cinder/volume/drivers/hpe/hpe_3par_common.py", line 545, in check_for_setup_error
2020-01-06 21:09:26.326 1 ERROR cinder     self.validate_cpg(cpg_name)
2020-01-06 21:09:26.326 1 ERROR cinder   File "/usr/lib/python2.7/site-packages/cinder/volume/drivers/hpe/hpe_3par_common.py", line 556, in validate_cpg
2020-01-06 21:09:26.326 1 ERROR cinder     raise exception.InvalidInput(reason=err)
2020-01-06 21:09:26.326 1 ERROR cinder InvalidInput: Invalid input received: CPG (S) doesn't exist on array
2020-01-06 21:09:26.326 1 ERROR cinder 
Exception AttributeError: "'NoneType' object has no attribute 'getcurrent'" in &lt;function _removeHandlerRef at 0x7f928df7a9b0&gt; ignored

</pre>
</body>

</html>
